In [1]:
import numpy as np

In [ ]:
# Numpy indexing nd slicing of vectors

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
# arr[3]
arr[1:11:1]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#Numpy indexing nd slicing of matrices

In [27]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [24]:
# arr[0]
# arr[1,4]
# slice=arr[0:2,1:3]
# slice
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
# Boolean Indexing

In [37]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [39]:
arr = arr[bool_index] #exreacts true values only basically array me bool_index daal diya
arr
#execution upar se lana vrna error dega and same line agar wapis se execute ke doge toh bhi error dega

array([12, 14, 16, 18, 20])