In [ ]:
#Arithmatic Operations

In [4]:
import numpy as np

In [8]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([10,11,12,13,14,15])    #to apply operation you ahve to take arrays of same size mtlb same number of elements hone chahiye

In [9]:
a1+a2

array([11, 13, 15, 17, 19, 21])

In [10]:
a1-a2

array([-9, -9, -9, -9, -9, -9])

In [11]:
a1*a2

array([10, 22, 36, 52, 70, 90])

In [12]:
a1/a2

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       ])

In [13]:
a1//a2

array([0, 0, 0, 0, 0, 0])

In [14]:
a1**a2

array([           1,         2048,       531441,     67108864,
         6103515625, 470184984576])

In [15]:
a1%a2

array([1, 2, 3, 4, 5, 6])

Broadcasting :
Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops.

In [34]:
l = [1,2,3,4]
arr=np.array(l)
arr+10
# agar ek sinlge element ko sabme add krna chah rhe ho tb broadcasting us ekr skte h

array([11, 12, 13, 14])

In [36]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [38]:
# Deep and Shallow copy

Deep Copy: Creates a completely independent copy of the object and all nested objects.
Shallow Copy: Creates a new outer object, but nested objects are shared with the original.

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice+10
slice

array([11, 12, 13, 14, 15])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
# b = a
b = a.copy()
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

smjho ab : basically ek ram h and usme ek array se kuch slice kroge to ram me kisi dusri location pr save hoge instead ki jaha pr array saved hai vhi ho but agar pura array ram se copy kroge toh same usi place pr save hoga like b = a kiya toh ab jaha a tha vhi b hoga isiliye b me changes krne pr a me bhi changes hue
yha isiiye b = a.copy kiya h taaki a me changes na ho and b ke pass a ki copy ajye and changes us copy me ho yhi hota h shallow copy 

In [18]:
# Matrix Operations

In [21]:
a = np.array([[1,2] , [4,5]])
b = np.array([[2,3] , [4,5]])

In [22]:
a

array([[1, 2],
       [4, 5]])

In [23]:
b

array([[2, 3],
       [4, 5]])

In [25]:
# a@b # @ is used for matrix multiplication 
np.dot(a,b)

array([[10, 13],
       [28, 37]])

In [27]:
# for transpose
a.T

array([[1, 4],
       [2, 5]])

In [28]:
b.T

array([[2, 4],
       [3, 5]])

In [29]:
# Adavnce Array manipulation

In [30]:
#stacking array 
# you can not stack matrices , you can stack vectors ( stack emans jodna matrices are already stacked)

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [40]:
np.vstack((a,b)) #ye vertically stack krta h jodta h yha ek ke neche dusra aata h 

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.hstack((a,b))#ye horizonatlly stack krta haijodta h , agar do array bhejoge to ek me jod dega ek ke baad dusra

array([1, 2, 3, 4, 5, 6])

In [42]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
#Splitting Array

In [51]:
c = np.arange(16).reshape(4,4)

In [52]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.hsplit(c,2) #3 me kroge to error aaega because equal divisions me krna hota h , horizontal me beech se  vertical cut hoga

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
a=np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [64]:
for i in a:
    print(i) #1-d me split nhi hoga 2-d me hi rhega , isme basically iterate krke 2 array de diye 2d me 

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
