In [4]:
import  numpy as np

In [2]:
#BASIC ARRAY CREATION
arr = np.array([1,2,3,])
arr

array([1, 2, 3])

In [8]:
a = [ 1 , 2 ,3 , 4.5 ,"hello"] #ye list hai
a

[1, 2, 3, 4.5, 'hello']

In [9]:
arr = np.array(a) #ye list ko array me coonvert kr dega
arr

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [7]:
# vectors are 1 dimensional 
# matrixes are 2 dimensional
# tensors are multidimensional , tensorflow suna hga

l = [[ 1,2 ,3] , [4,5,6] , [ 7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#ARRAY GENERATION FUNCTION
arr = np.arange(1,10,2)
arr
# same as python

array([1, 3, 5, 7, 9])

In [38]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,5,3)  #press shift + tab se desription aa jaegi  
arr

# used for linear spacing

array([1., 3., 5.])

In [48]:
arr = np.random.rand(5)
arr

array([0.76294929, 0.67075469, 0.78710302, 0.48542283, 0.05668795])

In [5]:
#RANDOM GENERATION FUNCTION
arr = np.random.rand(5) 
# random library already hoti h numpy me inbuilt bhi hoti h
arr
#normalisation ka concept use hua h 0 se 1 ke beech 5 numbers choose hoge

array([0.06514565, 0.12771815, 0.37461028, 0.73123477, 0.17843554])

In [6]:
arr = np.random.randn(5)
arr
#standardisation ka concept use hua h -3 se 3 ke beech 5 numbers choose hoge

array([-1.51646408, -0.3905553 ,  1.06498093, -0.08119465,  0.77103973])

In [18]:
arr = np.random.randint(10,20,10) 
#10 random numbers between 10 and 20
arr

array([10, 11, 16, 18, 11, 12, 18, 13, 11, 13], dtype=int32)

In [ ]:
# ARRAY ATTRIBUTES

In [25]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.size

9

In [27]:
arr.shape

(3, 3)

In [28]:
arr.dtype

dtype('int64')